[[headers]]
  for = "/msmarzewski.pl/*"
  [headers.values]
	X-Robots-Tag = "all"

[[headers]]
  for = "/www.msmarzewski.pl/*"
  [headers.values]
	X-Robots-Tag = "all"

[[headers]]
  for = "/smarzewski.netlify.app/*"
  [headers.values]
	X-Robots-Tag = "all"

# explicit commands for building the site
# and the folder to publish
[build]
command = "pnpm install && npm run build"
publish = "build"

[build.environment]
# cache Cypress binary in local "node_modules" folder
# so Netlify caches it
CYPRESS_CACHE_FOLDER = ".cypress/"
# set TERM variable for terminal output
TERM = "xterm"

[[plugins]]
# runs Cypress tests against the deployed URL
package = "netlify-plugin-cypress"

	[plugins.inputs]
		record = true
		browser = "webkit"
		configFile = "cypress.config.ts"