[[headers]]
  for = "/msmarzewski.pl/*"
  [headers.values]
	X-Robots-Tag = "all"

[[headers]]
  for = "/www.msmarzewski.pl/*"
  [headers.values]
	X-Robots-Tag = "all"

[[headers]]
  for = "/smarzewski.netlify.app/*"
  [headers.values]
	X-Robots-Tag = "all"

[build]
	command = "cypress install && npx playwright install && npm run test && npm run build"